set(LIBDAISY_DIR ./DaisyExamples/libDaisy)
set(DAISYSP_LIB_DIR ./DaisyExamples/DaisySP)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_C_STANDARD 11)
set(LINKER_SCRIPT ${LIBDAISY_DIR}/core/STM32H750IB_flash.lds)

set(MODULE_DIR "${LIBDAISY_DIR}/src")

add_library(libdaisy STATIC
        ${MODULE_DIR}/sys/dma.c
        ${MODULE_DIR}/hid/audio.cpp
        ${MODULE_DIR}/sys/fatfs.cpp
        ${MODULE_DIR}/per/gpio.cpp
        ${MODULE_DIR}/per/rng.cpp
        ${MODULE_DIR}/per/sai.cpp
        ${MODULE_DIR}/per/sdmmc.cpp
        ${MODULE_DIR}/util/bsp_sd_diskio.c
        ${MODULE_DIR}/util/hal_map.c
        ${MODULE_DIR}/util/oled_fonts.c
        ${MODULE_DIR}/util/sd_diskio.c
        ${MODULE_DIR}/util/usbh_diskio.c
        ${MODULE_DIR}/util/unique_id.c
        ${MODULE_DIR}/sys/system_stm32h7xx.c
        ${MODULE_DIR}/usbd/usbd_cdc_if.c
        ${MODULE_DIR}/usbd/usbd_desc.c
        ${MODULE_DIR}/usbd/usbd_conf.c
        ${MODULE_DIR}/usbh/usbh_conf.c
        ${MODULE_DIR}/daisy_seed.cpp
        ${MODULE_DIR}/daisy_pod.cpp
        ${MODULE_DIR}/daisy_patch.cpp
        ${MODULE_DIR}/daisy_petal.cpp
        ${MODULE_DIR}/daisy_field.cpp
        ${MODULE_DIR}/daisy_versio.cpp
        ${MODULE_DIR}/daisy_legio.cpp
        ${MODULE_DIR}/daisy_patch_sm.cpp
        ${MODULE_DIR}/sys/system.cpp
        ${MODULE_DIR}/dev/sr_595.cpp
        ${MODULE_DIR}/dev/codec_ak4556.cpp
        ${MODULE_DIR}/dev/codec_pcm3060.cpp
        ${MODULE_DIR}/dev/codec_wm8731.cpp
        ${MODULE_DIR}/dev/lcd_hd44780.cpp
        ${MODULE_DIR}/hid/ctrl.cpp
        ${MODULE_DIR}/hid/encoder.cpp
        ${MODULE_DIR}/hid/gatein.cpp
        ${MODULE_DIR}/hid/led.cpp
        ${MODULE_DIR}/hid/midi.cpp
        ${MODULE_DIR}/hid/midi_parser.cpp
        ${MODULE_DIR}/hid/parameter.cpp
        ${MODULE_DIR}/hid/rgb_led.cpp
        ${MODULE_DIR}/hid/switch.cpp
        ${MODULE_DIR}/hid/usb.cpp
        ${MODULE_DIR}/hid/usb_host.cpp
        ${MODULE_DIR}/hid/usb_midi.cpp
        ${MODULE_DIR}/hid/wavplayer.cpp
        ${MODULE_DIR}/hid/logger.cpp
        ${MODULE_DIR}/per/adc.cpp
        ${MODULE_DIR}/per/dac.cpp
        ${MODULE_DIR}/per/i2c.cpp
        ${MODULE_DIR}/per/qspi.cpp
        ${MODULE_DIR}/dev/sdram.cpp
        ${MODULE_DIR}/per/spi.cpp
        ${MODULE_DIR}/per/spiMultislave.cpp
        ${MODULE_DIR}/per/tim.cpp
        ${MODULE_DIR}/per/uart.cpp
        ${MODULE_DIR}/ui/AbstractMenu.cpp
        ${MODULE_DIR}/ui/FullScreenItemMenu.cpp
        ${MODULE_DIR}/ui/UI.cpp
        ${MODULE_DIR}/util/color.cpp
        ${MODULE_DIR}/util/WaveTableLoader.cpp

        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_msp_template.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_alarm_template.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_wakeup_template.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_tim_template.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_adc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_bdma.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_comp.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_crc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dac.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_delayblock.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma2d.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_exti.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_gpio.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_hrtim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_i2c.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lptim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lpuart.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_mdma.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_opamp.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_pwr.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rcc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rng.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rtc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_spi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_swpmi.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_tim.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usart.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_utils.c

        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_scsi.c
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c
        ${LIBDAISY_DIR}/Middlewares/Third_Party/FatFs/src/diskio.c
        ${LIBDAISY_DIR}/Middlewares/Third_Party/FatFs/src/ff.c
        ${LIBDAISY_DIR}/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c
        ${LIBDAISY_DIR}/core/startup_stm32h750xx.c
)

target_include_directories(libdaisy PRIVATE
        ${LIBDAISY_DIR}/Drivers/CMSIS/Include
        ${LIBDAISY_DIR}/Drivers/CMSIS/Device/ST/STM32H7xx/Include
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc
        ${LIBDAISY_DIR}/Middlewares/Third_Party/FatFs/src
        ${LIBDAISY_DIR}/src
        ${LIBDAISY_DIR}/src/sys
        ${LIBDAISY_DIR}/src/usbd
        ${LIBDAISY_DIR}/src/usbh
)
include_directories(
        ${LIBDAISY_DIR}/Drivers/CMSIS/Include
        ${LIBDAISY_DIR}/Drivers/CMSIS/Device/ST/STM32H7xx/Include
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc
        ${LIBDAISY_DIR}/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Core/Inc
        ${LIBDAISY_DIR}/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc
        ${LIBDAISY_DIR}/Middlewares/Third_Party/FatFs/src
        ${LIBDAISY_DIR}/src
        ${LIBDAISY_DIR}/src/sys
        ${LIBDAISY_DIR}/src/usbd
        ${LIBDAISY_DIR}/src/usbh
)
